### PR TITLE
Set ARCHFLAGS for osx-arm builds (Ice3.6), add Python 3.10

### PR DESCRIPTION
**Pull request by manics**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adds `recipe/osx.patch` to support Mac SDKs >=10.15, and some additional build arguments needed for the osx-arm64 build

Closes https://github.com/conda-forge/zeroc-ice-feedstock/issues/23

### CODE REVIEW

**Comment by manics** [comment]
@conda-forge-admin, please rerender

**Comment by manics** [comment]
@conda-forge-admin, please rerender

**Comment by manics** [comment]
@conda-forge-admin, please rerender

**Comment by manics** [comment]
Hi @psobolewskiPhD, please could you test this Ice 3.6 arm build?

1. Download the artifact from https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=490470&view=artifacts&pathAsName=false&type=publishedArtifacts, unzip, unzip again, and look for the `build_artifacts/` directory.
2. Run `conda create -n test --strict-channel-priority -c file://path/to/unzipped/build_artifacts/ -c conda-forge omero-py`, this should use the local `build_artifacts` directory as a local conda repository with higher precedence than conda-forge.
3. Activate the environment and run `conda list`, check that `zeroc-ice` comes from the local `build_artifacts`. If it didn't work try `conda install path/to/zeroc-ice-3.6.5-....tar.bz2` to overwrite whatever was installed.
3. Test it!

**Comment by psobolewskiPhD** [comment]
Looks good!
Install was fine...
```
lipo -info IcePy.cpython-39-darwin.so                               (test) ─╯
Non-fat file: IcePy.cpython-39-darwin.so is architecture: arm64
```
I can import IcePy...

Not sure how to test omero-py...

**Comment by manics** [comment]
omero-py includes the OMERO CLI, so things like `omero login ...` should work

**Comment by psobolewskiPhD** [comment]
> omero-py includes the OMERO CLI, so things like `omero login ...` should work

But what do I log into? I have no idea really what omero-py does, I was just trying to help someone with install issues on arm64.

**Comment by manics** [comment]
@psobolewskiPhD Don't worry then, thanks for helping out! I'll leave it to @joshmoore to decide whether to merge, or to seek out other testers.

**Comment by psobolewskiPhD** [comment]
If y'all can whip up something step-by-step (like you did here: https://github.com/conda-forge/zeroc-ice-feedstock/pull/24#issuecomment-1095516813 thank you!!) I can give it a whirl.
Just let me know 😄

**Comment by joshmoore** [comment]
I'd think `python -c "import omero.all"` would actually suffice.

**Comment by psobolewskiPhD** [comment]
> I'd think `python -c "import omero.all"` would actually suffice.

```
╭─    ~/dev ·························································· ✔ ─
╰─ python -c "import omero.all"                                        (test) ─╯
╭─    ~/dev ·························································· ✔ ─
╰─                                                                     (test) ─╯
```

Nothing happened—is this good?

**Comment by joshmoore** [comment]
Very. Thanks, @psobolewskiPhD. Merging.

**Pull request merged**
