### PR TITLE
migration: OSXArm (version_3.6 branch)

### PR DESCRIPTION
**Pull request by manics**
This is a manual port of https://github.com/conda-forge/zeroc-ice-feedstock/pull/20 to the `version_3.6` branch

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Related to https://github.com/ome/omero-py/issues/324

### CODE REVIEW

**Comment by manics** [comment]
@conda-forge-admin, please rerender

**Comment by manics** [comment]
@conda-forge-admin, please rerender

**Review by joshmoore — APPROVED** [review]
Thanks, @manics :heart: I have limited experience with these arm migrations (and no way to test the changes) but in general huge support for getting this out there for proper testing (assuming of course there are no downsides for existing builds 🙂 )

**Comment by manics** [comment]
I don't have any way to test either :smile: 
It should just add another build/deployment combination, and shouldn't affect any existing packages. Merge if you want to give it a go....

**Comment by joshmoore** [comment]
Let's do it! :shipit:

**Comment by psobolewskiPhD** [comment]
Hi, I'm willing to help test locally on my M1 if you can give me some instructions!

**Comment by joshmoore** [comment]
@psobolewskiPhD, great, thanks!

It looks like the files have been uploaded to https://anaconda.org/conda-forge/zeroc-ice/files

Screen Shot 2022-04-04 at 16 57 32

I assume `conda install -c conda-forge zeroc-ice=3.6.5` should let you try this out.

**Comment by psobolewskiPhD** [comment]
OK, so this JustWorks with arm64 miniforge
```
mamba create -y -n ice-test python=3.9
conda activate ice-test
mamba install omero-py 
```
But! Something isn't crosscompiled correctly, because:
```
>>> import omero.clients
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/ice-test/lib/python3.9/site-packages/omero/__init__.py", line 17, in <module>
    import Ice
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/ice-test/lib/python3.9/site-packages/Ice.py", line 47, in <module>
    import IcePy
ImportError: dlopen(/Users/piotrsobolewski/Dev/miniforge3/envs/ice-test/lib/python3.9/site-packages/IcePy.cpython-39-darwin.so, 0x0002): tried: '/Users/piotrsobolewski/Dev/miniforge3/envs/ice-test/lib/python3.9/site-packages/IcePy.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/IcePy.cpython-39-darwin.so' (no such file), '/usr/lib/IcePy.cpython-39-darwin.so' (no such file)
```

**Comment by manics** [comment]
I've added a new issue to track this https://github.com/conda-forge/zeroc-ice-feedstock/issues/23

**Pull request merged**
