### PR TITLE
Set ARCHFLAGS for osx-arm builds (Ice3.7)

### PR DESCRIPTION
**Pull request by manics**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by manics** [comment]
@conda-forge-admin, please rerender

**Comment by manics** [comment]
@psobolewskiPhD would you mind testing this for me? This PR has some artifacts you can download from:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=486796&view=artifacts&pathAsName=false&type=publishedArtifacts
Could you download one of the `osx_arm64` packages (look for the triple dot on the far right of the artifact to get the link), unzip it twice, and you should see a conda package under `osx-arm64`

Checking with file suggests it's arm64:
```
$ file lib/python3.9/site-packages/IcePy.cpython-39-darwin.so 
lib/python3.9/site-packages/IcePy.cpython-39-darwin.so: Mach-O 64-bit arm64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK>
```
But would be good if you can try it for real, if possible install it and see if you can load the Ice Python module.

**Comment by psobolewskiPhD** [comment]
I think it worked?
I unzipped, twice, went into osx-arm64, did `conda install <path o the .bz2>`:
```
Downloading and Extracting Packages
zeroc-ice-3.7.7      | ################################################# | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
Then in my env site-packages:
```
lipo -info IcePy.cpython-39-darwin.so                           (ice-test) ─╯
Non-fat file: IcePy.cpython-39-darwin.so is architecture: arm64
```
Not sure how/what else to test?

**Comment by psobolewskiPhD** [comment]
OK, with some trial and error:
```
>>> import IcePy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/piotrsobolewski/Dev/miniforge3/envs/ice-test/lib/python3.9/site-packages/IcePy.cpython-39-darwin.so, 0x0002): Symbol not found: _libiconv
  Referenced from: /Users/piotrsobolewski/Dev/miniforge3/envs/ice-test/lib/python3.9/site-packages/IcePy.cpython-39-darwin.so
  Expected in: /usr/lib/libiconv.2.dylib
>>> 
```
Hope that helps?

**Comment by manics** [comment]
Thanks!

> `Symbol not found: _libiconv`

This might be because installing the bz2 directly doesn't automatically resolve dependencies .... if it's OK with you I'll clean-up this PR, merge it, and then maybe you could test the published package in a clean environment?

**Comment by psobolewskiPhD** [comment]
> Thanks!
> 
> > `Symbol not found: _libiconv`
> 
> This might be because installing the bz2 directly doesn't automatically resolve dependencies .... if it's OK with you I'll clean-up this PR, merge it, and then maybe you could test the published package in a clean environment?

Sure thing—tomorrow tho, EU time here.

**Comment by manics** [comment]
Merging so this can be properly tested

**Comment by psobolewskiPhD** [comment]
Good news @manics in a fresh conda, `conda install zeroc-ice` gives arm64 now:
```
╰─ lipo -info IcePy.cpython-39-darwin.so                           (ice-test) ─╯
Non-fat file: IcePy.cpython-39-darwin.so is architecture: arm64
```
and IcePy is importable. Not sure how/what else I can test, but that seems good to go.

**Pull request merged**
